var allKMBRoutes = [
  {
    "route": "1",
    "bound": "O",
    "service_type": "1",
    "orig_en": "CHUK YUEN ESTATE",
    "orig_tc": "竹園邨",
    "orig_sc": "竹园邨",
    "dest_en": "STAR FERRY",
    "dest_tc": "尖沙咀碼頭",
    "dest_sc": "尖沙咀码头",
    "co": "KMB"
  },
  {
    "route": "1",
    "bound": "I",
    "service_type": "1",
    "orig_en": "STAR FERRY",
    "orig_tc": "尖沙咀碼頭",
    "orig_sc": "尖沙咀码头",
    "dest_en": "CHUK YUEN ESTATE",
    "dest_tc": "竹園邨",
    "dest_sc": "竹园邨",
    "co": "KMB"
  },
  {
    "route": "1A",
    "bound": "O",
    "service_type": "1",
    "orig_en": "SAU MAU PING (CENTRAL)",
    "orig_tc": "中秀茂坪",
    "orig_sc": "中秀茂坪",
    "dest_en": "STAR FERRY",
    "dest_tc": "尖沙咀碼頭",
    "dest_sc": "尖沙咀码头",
    "co": "KMB"
  },
  {
    "route": "1A",
    "bound": "I",
    "service_type": "1",
    "orig_en": "STAR FERRY",
    "orig_tc": "尖沙咀碼頭",
    "orig_sc": "尖沙咀码头",
    "dest_en": "SAU MAU PING (CENTRAL)",
    "dest_tc": "中秀茂坪",
    "dest_sc": "中秀茂坪",
    "co": "KMB"
  },
  {
    "route": "2",
    "bound": "O",
    "service_type": "1",
    "orig_en": "STAR FERRY",
    "orig_tc": "尖沙咀碼頭",
    "orig_sc": "尖沙咀码头",
    "dest_en": "CHEUNG SHA WAN (SO UK ESTATE)",
    "dest_tc": "長沙灣(蘇屋邨)",
    "dest_sc": "长沙湾(苏屋邨)",
    "co": "KMB"
  },
  {
    "route": "2",
    "bound": "I",
    "service_type": "1",
    "orig_en": "CHEUNG SHA WAN (SO UK ESTATE)",
    "orig_tc": "長沙灣(蘇屋邨)",
    "orig_sc": "长沙湾(苏屋邨)",
    "dest_en": "STAR FERRY",
    "dest_tc": "尖沙咀碼頭",
    "dest_sc": "尖沙咀码头",
    "co": "KMB"
  },
  {
    "route": "2A",
    "bound": "O",
    "service_type": "1",
    "orig_en": "LOK WAH",
    "orig_tc": "樂華",
    "orig_sc": "乐华",
    "dest_en": "MEI FOO",
    "dest_tc": "美孚",
    "dest_sc": "美孚",
    "co": "KMB"
  },
  {
    "route": "2A",
    "bound": "I",
    "service_type": "1",
    "orig_en": "MEI FOO",
    "orig_tc": "美孚",
    "orig_sc": "美孚",
    "dest_en": "LOK WAH",
    "dest_tc": "樂華",
    "dest_sc": "乐华",
    "co": "KMB"
  },
  {
    "route": "2B",
    "bound": "O",
    "service_type": "1",
    "orig_en": "CHUK YUEN ESTATE",
    "orig_tc": "竹園邨",
    "orig_sc": "竹园邨",
    "dest_en": "CHEUNG SHA WAN",
    "dest_tc": "長沙灣",
    "dest_sc": "长沙湾",
    "co": "KMB"
  },
  {
    "route": "2B",
    "bound": "I",
    "service_type": "1",
    "orig_en": "CHEUNG SHA WAN",
    "orig_tc": "長沙灣",
    "orig_sc": "长沙湾",
    "dest_en": "CHUK YUEN ESTATE",
    "dest_tc": "竹園邨",
    "dest_sc": "竹园邨",
    "co": "KMB"
  },
  {
    "route": "2D",
    "bound": "O",
    "service_type": "1",
    "orig_en": "CHAK ON ESTATE",
    "orig_tc": "澤安邨",
    "orig_sc": "泽安邨",
    "dest_en": "WONG TAI SIN",
    "dest_tc": "黃大仙",
    "dest_sc": "黄大仙",
    "co": "KMB"
  },
  {
    "route": "2D",
    "bound": "I",
    "service_type": "1",
    "orig_en": "WONG TAI SIN",
    "orig_tc": "黃大仙",
    "orig_sc": "黄大仙",
    "dest_en": "CHAK ON ESTATE",
    "dest_tc": "澤安邨",
    "dest_sc": "泽安邨",
    "co": "KMB"
  },
  {
    "route": "2E",
    "bound": "O",
    "service_type": "1",
    "orig_en": "KOWLOON CITY FERRY",
    "orig_tc": "九龍城碼頭",
    "orig_sc": "九龙城码头",
    "dest_en": "PAK TIN (NORTH)",
    "dest_tc": "白田(北)",
    "dest_sc": "白田(北)",
    "co": "KMB"
  },
  {
    "route": "2E",
    "bound": "I",
    "service_type": "1",
    "orig_en": "PAK TIN (NORTH)",
    "orig_tc": "白田(北)",
    "orig_sc": "白田(北)",
    "dest_en": "KOWLOON CITY FERRY",
    "dest_tc": "九龍城碼頭",
    "dest_sc": "九龙城码头",
    "co": "KMB"
  },
  {
    "route": "2F",
    "bound": "O",
    "service_type": "1",
    "orig_en": "TSZ WAN SHAN (NORTH)",
    "orig_tc": "慈雲山(北)",
    "orig_sc": "慈云山(北)",
    "dest_en": "CHEUNG SHA WAN",
    "dest_tc": "長沙灣",
    "dest_sc": "长沙湾",
    "co": "KMB"
  },
  {
    "route": "2F",
    "bound": "O",
    "service_type": "2",
    "orig_en": "TSZ WAN SHAN (NORTH)",
    "orig_tc": "慈雲山(北)",
    "orig_sc": "慈云山(北)",
    "dest_en": "CHEUNG SHA WAN",
    "dest_tc": "長沙灣",
    "dest_sc": "长沙湾",
    "co": "KMB"
  },
  {
    "route": "2F",
    "bound": "I",
    "service_type": "1",
    "orig_en": "CHEUNG SHA WAN",
    "orig_tc": "長沙灣",
    "orig_sc": "长沙湾",
    "dest_en": "TSZ WAN SHAN (NORTH)",
    "dest_tc": "慈雲山(北)",
    "dest_sc": "慈云山(北)",
    "co": "KMB"
  },
  {
    "route": "2P",
    "bound": "O",
    "service_type": "1",
    "orig_en": "CHEUNG SHA WAN",
    "orig_tc": "長沙灣",
    "orig_sc": "长沙湾",
    "dest_en": "TSZ WAN SHAN (NORTH)",
    "dest_tc": "慈雲山(北)",
    "dest_sc": "慈云山(北)",
    "co": "KMB"
  },
  {
    "route": "2X",
    "bound": "O",
    "service_type": "1",
    "orig_en": "CHOI FOOK",
    "orig_tc": "彩福",
    "orig_sc": "彩福",
    "dest_en": "MEI FOO",
    "dest_tc": "美孚",
    "dest_sc": "美孚",
    "co": "KMB"
  },
  {
    "route": "2X",
    "bound": "I",
    "service_type": "1",
    "orig_en": "MEI FOO",
    "orig_tc": "美孚",
    "orig_sc": "美孚",
    "dest_en": "CHOI FOOK",
    "dest_tc": "彩福",
    "dest_sc": "彩福",
    "co": "KMB"
  },
  {
    "route": "3B",
    "bound": "O",
    "service_type": "1",
    "orig_en": "TSZ WAN SHAN (CENTRAL)",
    "orig_tc": "慈雲山(中)",
    "orig_sc": "慈云山(中)",
    "dest_en": "HUNG HOM (HUNG LUEN ROAD)",
    "dest_tc": "紅磡(紅鸞道)",
    "dest_sc": "红磡(红鸾道)",
    "co": "KMB"
  },
  {
    "route": "3B",
    "bound": "I",
    "service_type": "1",
    "orig_en": "HUNG HOM (HUNG LUEN ROAD)",
    "orig_tc": "紅磡(紅鸞道)",
    "orig_sc": "红磡(红鸾道)",
    "dest_en": "TSZ WAN SHAN (CENTRAL)",
    "dest_tc": "慈雲山(中)",
    "dest_sc": "慈云山(中)",
    "co": "KMB"
  },
  {
    "route": "3B",
    "bound": "I",
    "service_type": "2",
    "orig_en": "HUNG HOM (HUNG LUEN ROAD)",
    "orig_tc": "紅磡(紅鸞道)",
    "orig_sc": "红磡(红鸾道)",
    "dest_en": "TSZ WAN SHAN (CENTRAL)",
    "dest_tc": "慈雲山(中)",
    "dest_sc": "慈云山(中)",
    "co": "KMB"
  },
  {
    "route": "3C",
    "bound": "O",
    "service_type": "1",
    "orig_en": "TSZ WAN SHAN (NORTH)",
    "orig_tc": "慈雲山(北)",
    "orig_sc": "慈云山(北)",
    "dest_en": "CHINA FERRY TERMINAL",
    "dest_tc": "中港碼頭",
    "dest_sc": "中港码头",
    "co": "KMB"
  },
  {
    "route": "3C",
    "bound": "I",
    "service_type": "1",
    "orig_en": "CHINA FERRY TERMINAL",
    "orig_tc": "中港碼頭",
    "orig_sc": "中港码头",
    "dest_en": "TSZ WAN SHAN (NORTH)",
    "dest_tc": "慈雲山(北)",
    "dest_sc": "慈云山(北)",
    "co": "KMB"
  },
  {
    "route": "3D",
    "bound": "O",
    "service_type": "1",
    "orig_en": "TSZ WAN SHAN (CENTRAL)",
    "orig_tc": "慈雲山(中)",
    "orig_sc": "慈云山(中)",
    "dest_en": "KWUN TONG (YUE MAN SQUARE)",
    "dest_tc": "觀塘(裕民坊)",
    "dest_sc": "观塘(裕民坊)",
    "co": "KMB"
  },
  {
    "route": "3D",
    "bound": "O",
    "service_type": "2",
    "orig_en": "TSZ WAN SHAN (SOUTH)",
    "orig_tc": "慈雲山(南)",
    "orig_sc": "慈云山(南)",
    "dest_en": "KWUN TONG (YUE MAN SQUARE)",
    "dest_tc": "觀塘(裕民坊)",
    "dest_sc": "观塘(裕民坊)",
    "co": "KMB"
  },
  {
    "route": "3D",
    "bound": "O",
    "service_type": "3",
    "orig_en": "CHING HONG HOUSE",
    "orig_tc": "正康樓",
    "orig_sc": "正康楼",
    "dest_en": "KWUN TONG (YUE MAN SQUARE)",
    "dest_tc": "觀塘(裕民坊)",
    "dest_sc": "观塘(裕民坊)",
    "co": "KMB"
  },
  {
    "route": "3D",
    "bound": "I",
    "service_type": "1",
    "orig_en": "KWUN TONG (YUE MAN SQUARE)",
    "orig_tc": "觀塘(裕民坊)",
    "orig_sc": "观塘(裕民坊)",
    "dest_en": "TSZ WAN SHAN (CENTRAL)",
    "dest_tc": "慈雲山(中)",
    "dest_sc": "慈云山(中)",
    "co": "KMB"
  },
  {
    "route": "3D",
    "bound": "I",
    "service_type": "2",
    "orig_en": "KWUN TONG (YUE MAN SQUARE)",
    "orig_tc": "觀塘(裕民坊)",
    "orig_sc": "观塘(裕民坊)",
    "dest_en": "TSZ WAN SHAN (SOUTH)",
    "dest_tc": "慈雲山(南)",
    "dest_sc": "慈云山(南)",
    "co": "KMB"
  },
  {
    "route": "3M",
    "bound": "O",
    "service_type": "1",
    "orig_en": "TSZ WAN SHAN (NORTH)",
    "orig_tc": "慈雲山(北)",
    "orig_sc": "慈云山(北)",
    "dest_en": "CHOI WAN",
    "dest_tc": "彩雲",
    "dest_sc": "彩云",
    "co": "KMB"
  },
  {
    "route": "3M",
    "bound": "I",
    "service_type": "1",
    "orig_en": "CHOI WAN",
    "orig_tc": "彩雲",
    "orig_sc": "彩云",
    "dest_en": "TSZ WAN SHAN (NORTH)",
    "dest_tc": "慈雲山(北)",
    "dest_sc": "慈云山(北)",
    "co": "KMB"
  },
  {
    "route": "3M",
    "bound": "I",
    "service_type": "2",
    "orig_en": "CHOI WAN",
    "orig_tc": "彩雲",
    "orig_sc": "彩云",
    "dest_en": "TSZ WAN SHAN (SOUTH)",
    "dest_tc": "慈雲山(南)",
    "dest_sc": "慈云山(南)",
    "co": "KMB"
  },
  {
    "route": "3S",
    "bound": "O",
    "service_type": "1",
    "orig_en": "DIAMOND HILL STATION",
    "orig_tc": "鑽石山站",
    "orig_sc": "钻石山站",
    "dest_en": "DIAMOND HILL CEMETERY (CIRCULAR)",
    "dest_tc": "鑽石山墳場(循環線)",
    "dest_sc": "钻石山坟场(循环线)",
    "co": "KMB"
  },
  {
    "route": "3X",
    "bound": "O",
    "service_type": "1",
    "orig_en": "TSZ WAN SHAN (NORTH)",
    "orig_tc": "慈雲山(北)",
    "orig_sc": "慈云山(北)",
    "dest_en": "CHINA FERRY TERMINAL",
    "dest_tc": "中港碼頭",
    "dest_sc": "中港码头",
    "co": "KMB"
  },
  {
    "route": "3X",
    "bound": "O",
    "service_type": "2",
    "orig_en": "TSZ WAN SHAN (NORTH)",
    "orig_tc": "慈雲山(北)",
    "orig_sc": "慈云山(北)",
    "dest_en": "CHINA FERRY TERMINAL",
    "dest_tc": "中港碼頭",
    "dest_sc": "中港码头",
    "co": "KMB"
  },
  {
    "route": "3X",
    "bound": "I",
    "service_type": "1",
    "orig_en": "JORDAN (WEST KOWLOON STATION)",
    "orig_tc": "佐敦(西九龍站)",
    "orig_sc": "佐敦(西九龙站)",
    "dest_en": "TSZ WAN SHAN (NORTH)",
    "dest_tc": "慈雲山(北)",
    "dest_sc": "慈云山(北)",
    "co": "KMB"
  },
  {
    "route": "5",
    "bound": "O",
    "service_type": "1",
    "orig_en": "FU SHAN ESTATE",
    "orig_tc": "富山邨",
    "orig_sc": "富山邨",
    "dest_en": "STAR FERRY",
    "dest_tc": "尖沙咀碼頭",
    "dest_sc": "尖沙咀码头",
    "co": "KMB"
  },
  {
    "route": "5",
    "bound": "I",
    "service_type": "1",
    "orig_en": "STAR FERRY",
    "orig_tc": "尖沙咀碼頭",
    "orig_sc": "尖沙咀码头",
    "dest_en": "FU SHAN ESTATE",
    "dest_tc": "富山邨",
    "dest_sc": "富山邨",
    "co": "KMB"
  },
  {
    "route": "5A",
    "bound": "O",
    "service_type": "1",
    "orig_en": "KAI TAK (KAI CHING ESTATE)",
    "orig_tc": "啟德(啟晴邨)",
    "orig_sc": "启德(启晴邨)",
    "dest_en": "STAR FERRY",
    "dest_tc": "尖沙咀碼頭",
    "dest_sc": "尖沙咀码头",
    "co": "KMB"
  },
  {
    "route": "5A",
    "bound": "I",
    "service_type": "1",
    "orig_en": "STAR FERRY",
    "orig_tc": "尖沙咀碼頭",
    "orig_sc": "尖沙咀码头",
    "dest_en": "KAI TAK (KAI CHING ESTATE)",
    "dest_tc": "啟德(啟晴邨)",
    "dest_sc": "启德(启晴邨)",
    "co": "KMB"
  },
  {
    "route": "5C",
    "bound": "O",
    "service_type": "1",
    "orig_en": "TSZ WAN SHAN (CENTRAL)",
    "orig_tc": "慈雲山(中)",
    "orig_sc": "慈云山(中)",
    "dest_en": "STAR FERRY",
    "dest_tc": "尖沙咀碼頭",
    "dest_sc": "尖沙咀码头",
    "co": "KMB"
  },
  {
    "route": "5C",
    "bound": "O",
    "service_type": "2",
    "orig_en": "YUK WAH STREET",
    "orig_tc": "毓華街",
    "orig_sc": "毓华街",
    "dest_en": "STAR FERRY",
    "dest_tc": "尖沙咀碼頭",
    "dest_sc": "尖沙咀码头",
    "co": "KMB"
  },
  {
    "route": "5C",
    "bound": "I",
    "service_type": "1",
    "orig_en": "STAR FERRY",
    "orig_tc": "尖沙咀碼頭",
    "orig_sc": "尖沙咀码头",
    "dest_en": "TSZ WAN SHAN (CENTRAL)",
    "dest_tc": "慈雲山(中)",
    "dest_sc": "慈云山(中)",
    "co": "KMB"
  },
  {
    "route": "5C",
    "bound": "I",
    "service_type": "2",
    "orig_en": "STAR FERRY",
    "orig_tc": "尖沙咀碼頭",
    "orig_sc": "尖沙咀码头",
    "dest_en": "TSZ WAN SHAN (CENTRAL)",
    "dest_tc": "慈雲山(中)",
    "dest_sc": "慈云山(中)",
    "co": "KMB"
  },
  {
    "route": "5D",
    "bound": "O",
    "service_type": "1",
    "orig_en": "TELFORD GARDENS",
    "orig_tc": "德福花園",
    "orig_sc": "德福花园",
    "dest_en": "HUNG HOM (CIRCULAR)",
    "dest_tc": "紅磡(循環線)",
    "dest_sc": "红磡(循环线)",
    "co": "KMB"
  },
  {
    "route": "5M",
    "bound": "O",
    "service_type": "1",
    "orig_en": "KAI TAK (TAK LONG ESTATE)",
    "orig_tc": "啟德(德朗邨)",
    "orig_sc": "启德(德朗邨)",
    "dest_en": "KOWLOON BAY STATION (CIRCULAR)",
    "dest_tc": "九龍灣站(循環線)",
    "dest_sc": "九龙湾站(循环线)",
    "co": "KMB"
  },
  {
    "route": "5P",
    "bound": "O",
    "service_type": "1",
    "orig_en": "TSZ WAN SHAN (CENTRAL)",
    "orig_tc": "慈雲山(中)",
    "orig_sc": "慈云山(中)",
    "dest_en": "STAR FERRY",
    "dest_tc": "尖沙咀碼頭",
    "dest_sc": "尖沙咀码头",
    "co": "KMB"
  },
  {
    "route": "5P",
    "bound": "I",
    "service_type": "1",
    "orig_en": "STAR FERRY",
    "orig_tc": "尖沙咀碼頭",
    "orig_sc": "尖沙咀码头",
    "dest_en": "TSZ WAN SHAN (CENTRAL)",
    "dest_tc": "慈雲山(中)",
    "dest_sc": "慈云山(中)",
    "co": "KMB"
  },
  {
    "route": "5R",
    "bound": "O",
    "service_type": "1",
    "orig_en": "KAI TAK CRUISE TERMINAL",
    "orig_tc": "啟德郵輪碼頭",
    "orig_sc": "启德邮轮码头",
    "dest_en": "KWUN TONG (apm) (CIRCULAR)",
    "dest_tc": "觀塘 (apm) (循環線)",
    "dest_sc": "观塘 (apm) (循环线)",
    "co": "KMB"
  },
  {
    "route": "5R",
    "bound": "O",
    "service_type": "2",
    "orig_en": "KAI TAK CRUISE TERMINAL",
    "orig_tc": "啟德郵輪碼頭",
    "orig_sc": "启德邮轮码头",
    "dest_en": "KWUN TONG (apm)",
    "dest_tc": "觀塘 (apm)",
    "dest_sc": "观塘 (apm)",
    "co": "KMB"
  },
  {
    "route": "5R",
    "bound": "O",
    "service_type": "3",
    "orig_en": "NGAU TAU KOK STATION",
    "orig_tc": "牛頭角站",
    "orig_sc": "牛头角站",
    "dest_en": "KAI TAK CRUISE TERMINAL",
    "dest_tc": "啟德郵輪碼頭",
    "dest_sc": "启德邮轮码头",
    "co": "KMB"
  },
  {
    "route": "5R",
    "bound": "O",
    "service_type": "4",
    "orig_en": "NGAU TAU KOK STATION",
    "orig_tc": "牛頭角站",
    "orig_sc": "牛头角站",
    "dest_en": "SHING FUNG ROAD",
    "dest_tc": "承豐道",
    "dest_sc": "承丰道",
    "co": "KMB"
  },
  {
    "route": "5R",
    "bound": "O",
    "service_type": "5",
    "orig_en": "KAI TAK (SHENG KING STREET)",
    "orig_tc": "啟德(承景街)",
    "orig_sc": "启德(承景街)",
    "dest_en": "KWUN TONG (apm)",
    "dest_tc": "觀塘 (apm)",
    "dest_sc": "观塘 (apm)",
    "co": "KMB"
  },
  {
    "route": "6",
    "bound": "O",
    "service_type": "1",
    "orig_en": "STAR FERRY",
    "orig_tc": "尖沙咀碼頭",
    "orig_sc": "尖沙咀码头",
    "dest_en": "LAI CHI KOK",
    "dest_tc": "荔枝角",
    "dest_sc": "荔枝角",
    "co": "KMB"
  },
  {
    "route": "6",
    "bound": "I",
    "service_type": "1",
    "orig_en": "LAI CHI KOK",
    "orig_tc": "荔枝角",
    "orig_sc": "荔枝角",
    "dest_en": "STAR FERRY",
    "dest_tc": "尖沙咀碼頭",
    "dest_sc": "尖沙咀码头",
    "co": "KMB"
  },
  {
    "route": "6C",
    "bound": "O",
    "service_type": "1",
    "orig_en": "KOWLOON CITY FERRY",
    "orig_tc": "九龍城碼頭",
    "orig_sc": "九龙城码头",
    "dest_en": "MEI FOO",
    "dest_tc": "美孚",
    "dest_sc": "美孚",
    "co": "KMB"
  },
  {
    "route": "6C",
    "bound": "I",
    "service_type": "1",
    "orig_en": "MEI FOO",
    "orig_tc": "美孚",
    "orig_sc": "美孚",
    "dest_en": "KOWLOON CITY FERRY",
    "dest_tc": "九龍城碼頭",
    "dest_sc": "九龙城码头",
    "co": "KMB"
  },
  {
    "route": "6D",
    "bound": "O",
    "service_type": "1",
    "orig_en": "NGAU TAU KOK",
    "orig_tc": "牛頭角",
    "orig_sc": "牛头角",
    "dest_en": "MEI FOO",
    "dest_tc": "美孚",
    "dest_sc": "美孚",
    "co": "KMB"
  },
  {
    "route": "6D",
    "bound": "I",
    "service_type": "1",
    "orig_en": "MEI FOO",
    "orig_tc": "美孚",
    "orig_sc": "美孚",
    "dest_en": "NGAU TAU KOK",
    "dest_tc": "牛頭角",
    "dest_sc": "牛头角",
    "co": "KMB"
  },
  {
    "route": "6E",
    "bound": "O",
    "service_type": "1",
    "orig_en": "CHEUNG SHA WAN (SO UK ESTATE)",
    "orig_tc": "長沙灣(蘇屋邨)",
    "orig_sc": "长沙湾(苏屋邨)",
    "dest_en": "LEI YUE MUN ESTATE",
    "dest_tc": "鯉魚門邨",
    "dest_sc": "鲤鱼门邨",
    "co": "KMB"
  },
  {
    "route": "6E",
    "bound": "I",
    "service_type": "1",
    "orig_en": "LEI YUE MUN ESTATE",
    "orig_tc": "鯉魚門邨",
    "orig_sc": "鲤鱼门邨",
    "dest_en": "CHEUNG SHA WAN (SO UK ESTATE)",
    "dest_tc": "長沙灣(蘇屋邨)",
    "dest_sc": "长沙湾(苏屋邨)",
    "co": "KMB"
  },
  {
    "route": "6F",
    "bound": "O",
    "service_type": "1",
    "orig_en": "KOWLOON CITY FERRY",
    "orig_tc": "九龍城碼頭",
    "orig_sc": "九龙城码头",
    "dest_en": "CHEUNG SHA WAN (LAI KOK ESTATE)",
    "dest_tc": "長沙灣(麗閣邨)",
    "dest_sc": "长沙湾(丽阁邨)",
    "co": "KMB"
  },
  {
    "route": "6F",
    "bound": "I",
    "service_type": "1",
    "orig_en": "CHEUNG SHA WAN (LAI KOK ESTATE)",
    "orig_tc": "長沙灣(麗閣邨)",
    "orig_sc": "长沙湾(丽阁邨)",
    "dest_en": "KOWLOON CITY FERRY",
    "dest_tc": "九龍城碼頭",
    "dest_sc": "九龙城码头",
    "co": "KMB"
  },
  {
    "route": "6P",
    "bound": "O",
    "service_type": "1",
    "orig_en": "CHEUNG SHA WAN (SO UK ESTATE)",
    "orig_tc": "長沙灣(蘇屋邨)",
    "orig_sc": "长沙湾(苏屋邨)",
    "dest_en": "LEI YUE MUN ESTATE",
    "dest_tc": "鯉魚門邨",
    "dest_sc": "鲤鱼门邨",
    "co": "KMB"
  },
  {
    "route": "6P",
    "bound": "I",
    "service_type": "1",
    "orig_en": "LEI YUE MUN ESTATE",
    "orig_tc": "鯉魚門邨",
    "orig_sc": "鲤鱼门邨",
    "dest_en": "CHEUNG SHA WAN (SO UK ESTATE)",
    "dest_tc": "長沙灣(蘇屋邨)",
    "dest_sc": "长沙湾(苏屋邨)",
    "co": "KMB"
  },
  {
    "route": "6R",
    "bound": "O",
    "service_type": "1",
    "orig_en": "MEI FOO (MEI LAI ROAD)",
    "orig_tc": "美孚(美荔道)",
    "orig_sc": "美孚(美荔道)",
    "dest_en": "NGONG SHUEN CHAU BARRACKS (CIRCULAR)",
    "dest_tc": "昂船洲軍營(循環線)",
    "dest_sc": "昂船洲军营(循环线)",
    "co": "KMB"
  },
  {
    "route": "6X",
    "bound": "O",
    "service_type": "1",
    "orig_en": "SHING TAK STREET",
    "orig_tc": "盛德街",
    "orig_sc": "盛德街",
    "dest_en": "MEI FOO",
    "dest_tc": "美孚",
    "dest_sc": "美孚",
    "co": "KMB"
  },
  {
    "route": "6X",
    "bound": "I",
    "service_type": "1",
    "orig_en": "MEI FOO",
    "orig_tc": "美孚",
    "orig_sc": "美孚",
    "dest_en": "KOWLOON CITY FERRY",
    "dest_tc": "九龍城碼頭",
    "dest_sc": "九龙城码头",
    "co": "KMB"
  },
  {
    "route": "7",
    "bound": "O",
    "service_type": "1",
    "orig_en": "STAR FERRY",
    "orig_tc": "尖沙咀碼頭",
    "orig_sc": "尖沙咀码头",
    "dest_en": "LOK FU",
    "dest_tc": "樂富",
    "dest_sc": "乐富",
    "co": "KMB"
  },
  {
    "route": "7",
    "bound": "I",
    "service_type": "1",
    "orig_en": "LOK FU",
    "orig_tc": "樂富",
    "orig_sc": "乐富",
    "dest_en": "STAR FERRY",
    "dest_tc": "尖沙咀碼頭",
    "dest_sc": "尖沙咀码头",
    "co": "KMB"
  },
  {
    "route": "7B",
    "bound": "O",
    "service_type": "1",
    "orig_en": "HUNG HOM (HUNG LUEN ROAD)",
    "orig_tc": "紅磡(紅鸞道)",
    "orig_sc": "红磡(红鸾道)",
    "dest_en": "LOK FU",
    "dest_tc": "樂富",
    "dest_sc": "乐富",
    "co": "KMB"
  },
  {
    "route": "7B",
    "bound": "I",
    "service_type": "1",
    "orig_en": "LOK FU",
    "orig_tc": "樂富",
    "orig_sc": "乐富",
    "dest_en": "HUNG HOM (HUNG LUEN ROAD)",
    "dest_tc": "紅磡(紅鸞道)",
    "dest_sc": "红磡(红鸾道)",
    "co": "KMB"
  },
  {
    "route": "7M",
    "bound": "O",
    "service_type": "1",
    "orig_en": "LOK FU",
    "orig_tc": "樂富",
    "orig_sc": "乐富",
    "dest_en": "CHUK YUEN ESTATE (CIRCULAR)",
    "dest_tc": "竹園邨(循環線)",
    "dest_sc": "竹园邨(循环线)",
    "co": "KMB"
  },
  {
    "route": "8",
    "bound": "O",
    "service_type": "1",
    "orig_en": "STAR FERRY",
    "orig_tc": "尖沙咀碼頭",
    "orig_sc": "尖沙咀码头",
    "dest_en": "KOWLOON STATION",
    "dest_tc": "九龍站",
    "dest_sc": "九龙站",
    "co": "KMB"
  },
  {
    "route": "8",
    "bound": "I",
    "service_type": "1",
    "orig_en": "KOWLOON STATION",
    "orig_tc": "九龍站",
    "orig_sc": "九龙站",
    "dest_en": "STAR FERRY",
    "dest_tc": "尖沙咀碼頭",
    "dest_sc": "尖沙咀码头",
    "co": "KMB"
  },
  {
    "route": "8A",
    "bound": "O",
    "service_type": "1",
    "orig_en": "WHAMPOA GARDEN",
    "orig_tc": "黃埔花園",
    "orig_sc": "黄埔花园",
    "dest_en": "TSIM SHA TSUI (CIRCULAR)",
    "dest_tc": "尖沙咀(循環線)",
    "dest_sc": "尖沙咀(循环线)",
    "co": "KMB"
  },
  {
    "route": "8P",
    "bound": "O",
    "service_type": "1",
    "orig_en": "LAGUNA VERDE",
    "orig_tc": "海逸豪園",
    "orig_sc": "海逸豪园",
    "dest_en": "TSIM SHA TSUI (CIRCULAR)",
    "dest_tc": "尖沙咀(循環線)",
    "dest_sc": "尖沙咀(循环线)",
    "co": "KMB"
  },
  {
    "route": "8P",
    "bound": "O",
    "service_type": "2",
    "orig_en": "LAGUNA VERDE",
    "orig_tc": "海逸豪園",
    "orig_sc": "海逸豪园",
    "dest_en": "TSIM SHA TSUI",
    "dest_tc": "尖沙咀漢口道",
    "dest_sc": "尖沙咀汉口道",
    "co": "KMB"
  },
  {
    "route": "9",
    "bound": "O",
    "service_type": "1",
    "orig_en": "CHOI FOOK",
    "orig_tc": "彩福",
    "orig_sc": "彩福",
    "dest_en": "TSIM SHA TSUI EAST (MODY ROAD)",
    "dest_tc": "尖沙咀東(麼地道)",
    "dest_sc": "尖沙咀东(么地道)",
    "co": "KMB"
  },
  {
    "route": "9",
    "bound": "I",
    "service_type": "1",
    "orig_en": "TSIM SHA TSUI EAST (MODY ROAD)",
    "orig_tc": "尖沙咀東(麼地道)",
    "orig_sc": "尖沙咀东(么地道)",
    "dest_en": "CHOI FOOK",
    "dest_tc": "彩福",
    "dest_sc": "彩福",
    "co": "KMB"
  },
  {
    "route": "10",
    "bound": "O",
    "service_type": "1",
    "orig_en": "CHOI WAN",
    "orig_tc": "彩雲",
    "orig_sc": "彩云",
    "dest_en": "TAI KOK TSUI (CIRCULAR)",
    "dest_tc": "大角咀(循環線)",
    "dest_sc": "大角咀(循环线)",
    "co": "KMB"
  },
  {
    "route": "11",
    "bound": "O",
    "service_type": "1",
    "orig_en": "DIAMOND HILL STATION",
    "orig_tc": "鑽石山站",
    "orig_sc": "钻石山站",
    "dest_en": "KOWLOON STATION",
    "dest_tc": "九龍站",
    "dest_sc": "九龙站",
    "co": "KMB"
  },
  {
    "route": "11",
    "bound": "I",
    "service_type": "1",
    "orig_en": "KOWLOON STATION",
    "orig_tc": "九龍站",
    "orig_sc": "九龙站",
    "dest_en": "DIAMOND HILL STATION",
    "dest_tc": "鑽石山站",
    "dest_sc": "钻石山站",
    "co": "KMB"
  },
  {
    "route": "11B",
    "bound": "O",
    "service_type": "1",
    "orig_en": "KWUN TONG (TSUI PING ROAD)",
    "orig_tc": "觀塘(翠屏道)",
    "orig_sc": "观塘(翠屏道)",
    "dest_en": "KOWLOON CITY FERRY",
    "dest_tc": "九龍城碼頭",
    "dest_sc": "九龙城码头",
    "co": "KMB"
  },
  {
    "route": "11B",
    "bound": "I",
    "service_type": "1",
    "orig_en": "KOWLOON CITY FERRY",
    "orig_tc": "九龍城碼頭",
    "orig_sc": "九龙城码头",
    "dest_en": "KWUN TONG (TSUI PING ROAD)",
    "dest_tc": "觀塘(翠屏道)",
    "dest_sc": "观塘(翠屏道)",
    "co": "KMB"
  },
  {
    "route": "11C",
    "bound": "O",
    "service_type": "1",
    "orig_en": "CHUK YUEN ESTATE",
    "orig_tc": "竹園邨",
    "orig_sc": "竹园邨",
    "dest_en": "SAU MAU PING (UPPER)",
    "dest_tc": "上秀茂坪",
    "dest_sc": "上秀茂坪",
    "co": "KMB"
  },
  {
    "route": "11C",
    "bound": "I",
    "service_type": "1",
    "orig_en": "SAU MAU PING (UPPER)",
    "orig_tc": "上秀茂坪",
    "orig_sc": "上秀茂坪",
    "dest_en": "CHUK YUEN ESTATE",
    "dest_tc": "竹園邨",
    "dest_sc": "竹园邨",
    "co": "KMB"
  },
  {
    "route": "11D",
    "bound": "O",
    "service_type": "1",
    "orig_en": "LOK FU",
    "orig_tc": "樂富",
    "orig_sc": "乐富",
    "dest_en": "KWUN TONG FERRY",
    "dest_tc": "觀塘碼頭",
    "dest_sc": "观塘码头",
    "co": "KMB"
  },
  {
    "route": "11D",
    "bound": "I",
    "service_type": "1",
    "orig_en": "KWUN TONG FERRY",
    "orig_tc": "觀塘碼頭",
    "orig_sc": "观塘码头",
    "dest_en": "LOK FU",
    "dest_tc": "樂富",
    "dest_sc": "乐富",
    "co": "KMB"
  },
  {
    "route": "11K",
    "bound": "O",
    "service_type": "1",
    "orig_en": "CHUK YUEN ESTATE",
    "orig_tc": "竹園邨",
    "orig_sc": "竹园邨",
    "dest_en": "HUNG HOM STATION",
    "dest_tc": "紅磡站",
    "dest_sc": "红磡站",
    "co": "KMB"
  },
  {
    "route": "11K",
    "bound": "I",
    "service_type": "1",
    "orig_en": "HUNG HOM STATION",
    "orig_tc": "紅磡站",
    "orig_sc": "红磡站",
    "dest_en": "CHUK YUEN ESTATE",
    "dest_tc": "竹園邨",
    "dest_sc": "竹园邨",
    "co": "KMB"
  },
  {
    "route": "11X",
    "bound": "O",
    "service_type": "1",
    "orig_en": "ON TAI (NORTH)",
    "orig_tc": "安泰(北)",
    "orig_sc": "安泰(北)",
    "dest_en": "HUNG HOM STATION",
    "dest_tc": "紅磡站",
    "dest_sc": "红磡站",
    "co": "KMB"
  },
  {
    "route": "11X",
    "bound": "I",
    "service_type": "1",
    "orig_en": "HUNG HOM STATION",
    "orig_tc": "紅磡站",
    "orig_sc": "红磡站",
    "dest_en": "ON TAI (NORTH)",
    "dest_tc": "安泰(北)",
    "dest_sc": "安泰(北)",
    "co": "KMB"
  },
  {
    "route": "12",
    "bound": "O",
    "service_type": "1",
    "orig_en": "HOI LAI ESTATE",
    "orig_tc": "海麗邨",
    "orig_sc": "海丽邨",
    "dest_en": "TSIM SHA TSUI EAST (MODY ROAD)",
    "dest_tc": "尖沙咀東(麼地道)",
    "dest_sc": "尖沙咀东(么地道)",
    "co": "KMB"
  },
  {
    "route": "12",
    "bound": "I",
    "service_type": "1",
    "orig_en": "TSIM SHA TSUI EAST (MODY ROAD)",
    "orig_tc": "尖沙咀東(麼地道)",
    "orig_sc": "尖沙咀东(么地道)",
    "dest_en": "HOI LAI ESTATE",
    "dest_tc": "海麗邨",
    "dest_sc": "海丽邨",
    "co": "KMB"
  },
  {
    "route": "12A",
    "bound": "O",
    "service_type": "1",
    "orig_en": "WHAMPOA GARDEN",
    "orig_tc": "黃埔花園",
    "orig_sc": "黄埔花园",
    "dest_en": "CHEUNG SHA WAN (HOI TAT ESTATE)",
    "dest_tc": "長沙灣(海達邨)",
    "dest_sc": "长沙湾(海达邨)",
    "co": "KMB"
  },
  {
    "route": "12A",
    "bound": "I",
    "service_type": "1",
    "orig_en": "CHEUNG SHA WAN (HOI TAT ESTATE)",
    "orig_tc": "長沙灣(海達邨)",
    "orig_sc": "长沙湾(海达邨)",
    "dest_en": "WHAMPOA GARDEN",
    "dest_tc": "黃埔花園",
    "dest_sc": "黄埔花园",
    "co": "KMB"
  },
  {
    "route": "12P",
    "bound": "O",
    "service_type": "1",
    "orig_en": "Hoi Lai Estate",
    "orig_tc": "海麗邨",
    "orig_sc": "海丽邨",
    "dest_en": "Hung Hom Station",
    "dest_tc": "紅磡站",
    "dest_sc": "红磡站",
    "co": "KMB"
  },
  {
    "route": "13D",
    "bound": "O",
    "service_type": "1",
    "orig_en": "PO TAT",
    "orig_tc": "寶達",
    "orig_sc": "宝达",
    "dest_en": "ISLAND HARBOURVIEW",
    "dest_tc": "維港灣",
    "dest_sc": "维港湾",
    "co": "KMB"
  },
  {
    "route": "13D",
    "bound": "O",
    "service_type": "2",
    "orig_en": "PO TAT",
    "orig_tc": "寶達",
    "orig_sc": "宝达",
    "dest_en": "ISLAND HARBOURVIEW",
    "dest_tc": "維港灣",
    "dest_sc": "维港湾",
    "co": "KMB"
  }
  // Note: The original data was truncated here, so I’ve included up to "13D". Let me know if you have more routes to include!
];

// Placeholder for stop details (not provided in your KMB data yet)
var allKMBStops = [
  // Example format based on your Citybus data
  // {
  //   "stop": "FFB9E8929671D06E",
  //   "name_en": "Example Stop",
  //   "lat": "22.123456",
  //   "long": "114.123456"
  // }
  // Add your KMB stop data here when available
];

// Route-to-stops mapping renamed
var routeKMBStopsMap = {
  "PN19-o": [
    "FFB9E8929671D06E",
    "E33098F43CF205B8",
    "0524415976F284A4",
    "85A65BCDD35803A8",
    "0524415976F284A4",
    "E33098F43CF205B8",
    "FFB9E8929671D06E"
  ],
  "PN20-o": [
    "EB3F46E0040B4960",
    "9ADF943CA573C631",
    "23EC94A5FAA1E5A3",
    "6F4C27D4E845432E",
    "23EC94A5FAA1E5A3",
    "9ADF943CA573C631",
    "EB3F46E0040B4960"
  ],
  "R230-o": [
    "B97161BE6BCBD04D",
    "38C7D227DA221E77",
    "1FBE6A92A88835D3",
    "CF2B9E9382183398",
    "C5C940CF1281B923",
    "5941DC3E9FA7BE8B",
    "101877D46F079B68",
    "92A8281D80524F78",
    "F9F75324B8F1D7E3",
    "3357B55DE2539CA3",
    "A0C0A82ECC740D76",
    "6825AAECA55E0B01",
    "353B45E1D051707D",
    "9CFF3C233ADB8D19",
    "170375F0819EB588",
    "F2508598F5A43655",
    "1E5EADCD9F424F07"
  ],
  "R241-o": [
    "26AC2D471648CA0C",
    "F88EE882E4B77399",
    "CC13DC33AE269FB1",
    "4E870B220826BEE0",
    "5AD2A4D21C226335",
    "A454170B2B59B587",
    "D6E7412666B1175B",
    "AB87BD2749FFEACA",
    "43398296F1D1BD48",
    "67F3E54FF145BA65",
    "F02CE37AD01DF17E",
    "DFB7FD5832A4BA4E",
    "3406C1A9DA760403",
    "A3D1F413719E60F1",
    "B085DDE8E381E370",
    "F2508598F5A43655",
    "1E5EADCD9F424F07"
  ],
  "R33-o": [
    "E3E26EC8322AC889",
    "4B5144408E60BF11",
    "B651E2A39CD4CC05",
    "F734736F35F459DC",
    "23B913EACE0581E4",
    "C6D5DEF91CB7B581",
    "4566E35B3D2C20B5",
    "5055F6D68F0DD49D",
    "4D02E857ADDE8AAF",
    "818F12340BA8CA4B",
    "D74B67D55C63895F",
    "E3E26EC8322AC889",
    "6314A92BE85A8A9A",
    "4B5144408E60BF11",
    "B651E2A39CD4CC05",
    "F734736F35F459DC",
    "23B913EACE0581E4",
    "C6D5DEF91CB7B581",
    "4566E35B3D2C20B5",
    "5055F6D68F0DD49D",
    "4D02E857ADDE8AAF",
    "818F12340BA8CA4B",
    "D74B67D55C63895F"
  ],
  "R33-i": [
    "D74B67D55C63895F",
    "249DF4A1B287E14F",
    "AF9FE138E3D5D5F0",
    "1D44677AEFBA8773",
    "18580F35B0A312CF",
    "40ADE0A2BB16271A",
    "333A88A8E07C956B",
    "B2442AC56532517B",
    "78644FF7E8B7BBA0",
    "0221966C1116C4EC",
    "4F3D6BA55D5FFFE1",
    "FE235D7DCABCA944",
    "D74B67D55C63895F",
    "249DF4A1B287E14F",
    "AF9FE138E3D5D5F0",
    "1D44677AEFBA8773",
    "18580F35B0A312CF",
    "40ADE0A2BB16271A",
    "333A88A8E07C956B",
    "B2442AC56532517B",
    "78644FF7E8B7BBA0",
    "0221966C1116C4EC",
    "4F3D6BA55D5FFFE1",
    "5971529D89929BEA",
    "FE235D7DCABCA944"
  ],
  // ... (remaining route stops mappings unchanged, just renamed)
  "X89D-i": [
    "2D3C0F18F9131DA2",
    "70CD99F4D487740A",
    "D39533060940818A",
    "A1C35E976ACF46FD",
    "1E71CBFE8560B0EF",
    "C57C924EEB5463E5",
    "0209A3C455B1DBE9",
    "4B5F39DBC6671C81",
    "4CC126E0B1E42F14",
    "A90443FD0C19C4B1",
    "0CB1F7979192FBB2",
    "2C5CA5F47FB6EB3F",
    "10E07C1870465E91"
  ]
};