console.log("stations.js loaded");
const lines = {
    "AEL": [
        { value: "AIR", text: "Airport" },
        { value: "AWE", text: "AsiaWorld Expo" },
        { value: "HOK", text: "Hong Kong" },
        { value: "KOW", text: "Kowloon" },
        { value: "TSY", text: "Tsing Yi" }
    ],
    "TCL": [
        { value: "HOK", text: "Hong Kong" },
        { value: "KOW", text: "Kowloon" },
        { value: "LAK", text: "Lai King" },
        { value: "NAC", text: "Nam Cheong" },
        { value: "OLY", text: "Olympic" },
        { value: "SUN", text: "Sunny Bay" },
        { value: "TSY", text: "Tsing Yi" },
        { value: "TUC", text: "Tung Chung" }
    ],
    "TML": [
        { value: "AUS", text: "Austin" },
        { value: "CKT", text: "Che Kung Temple" },
        { value: "CIO", text: "City One" },
        { value: "DIH", text: "Diamond Hill" },
        { value: "ETS", text: "East Tsim Sha Tsui" },
        { value: "FOT", text: "Fo Tan" },
        { value: "HEO", text: "Heung Yuen Wai" },
        { value: "HIK", text: "Hin Keng" },
        { value: "HOM", text: "Ho Man Tin" },
        { value: "HUH", text: "Hung Hom" },
        { value: "KAT", text: "Kai Tak" },
        { value: "KSR", text: "Kam Sheung Road" },
        { value: "LOP", text: "Long Ping" },
        { value: "MOS", text: "Ma On Shan" },
        { value: "MEF", text: "Mei Foo" },
        { value: "NAC", text: "Nam Cheong" },
        { value: "SIH", text: "Siu Hong" },
        { value: "SHT", text: "Sha Tin" },
        { value: "STW", text: "Sha Tin Wai" },
        { value: "SHM", text: "Shek Mun" },
        { value: "SUW", text: "Sung Wong Toi" },
        { value: "TAW", text: "Tai Wai" },
        { value: "TSH", text: "Tai Shui Hang" },
        { value: "TIS", text: "Tin Shui Wai" },
        { value: "TKW", text: "To Kwa Wan" },
        { value: "TWW", text: "Tsuen Wan West" },
        { value: "TUM", text: "Tuen Mun" },
        { value: "UNI", text: "University" },
        { value: "WKS", text: "Wu Kai Sha" },
        { value: "YUL", text: "Yuen Long" }
    ],
    "TKL": [
        { value: "HAH", text: "Hang Hau" },
        { value: "LHP", text: "LOHAS Park" },
        { value: "NOP", text: "North Point" },
        { value: "POA", text: "Po Lam" },
        { value: "QUB", text: "Quarry Bay" },
        { value: "TIK", text: "Tiu Keng Leng" },
        { value: "TKO", text: "Tseung Kwan O" },
        { value: "YAT", text: "Yau Tong" }
    ],
    "EAL": [
        { value: "ADM", text: "Admiralty" },
        { value: "EXC", text: "Exhibition Centre" },
        { value: "FAN", text: "Fanling" },
        { value: "FOT", text: "Fo Tan" },
        { value: "HUH", text: "Hung Hom" },
        { value: "KOT", text: "Kowloon Tong" },
        { value: "LOW", text: "Lo Wu" },
        { value: "LMC", text: "Lok Ma Chau" },
        { value: "MKK", text: "Mong Kok East" },
        { value: "RAC", text: "Racecourse" },
        { value: "SHT", text: "Sha Tin" },
        { value: "SHS", text: "Sheung Shui" },
        { value: "TAP", text: "Tai Po Market" },
        { value: "TAW", text: "Tai Wai" },
        { value: "TWO", text: "Tai Wo" },
        { value: "UNI", text: "University" }
    ],
    "SIL": [
        { value: "ADM", text: "Admiralty" },
        { value: "LET", text: "Lei Tung" },
        { value: "OCP", text: "Ocean Park" },
        { value: "SOH", text: "South Horizons" },
        { value: "WCH", text: "Wong Chuk Hang" }
    ],
    "TWL": [
        { value: "ADM", text: "Admiralty" },
        { value: "CEN", text: "Central" },
        { value: "CSW", text: "Cheung Sha Wan" },
        { value: "JOR", text: "Jordan" },
        { value: "KWF", text: "Kwai Fong" },
        { value: "KWH", text: "Kwai Hing" },
        { value: "LCK", text: "Lai Chi Kok" },
        { value: "LAK", text: "Lai King" },
        { value: "MEF", text: "Mei Foo" },
        { value: "MOK", text: "Mong Kok" },
        { value: "PRE", text: "Prince Edward" },
        { value: "SSP", text: "Sham Shui Po" },
        { value: "TWH", text: "Tai Wo Hau" },
        { value: "TSW", text: "Tsuen Wan" },
        { value: "TST", text: "Tsim Sha Tsui" },
        { value: "YMT", text: "Yau Ma Tei" }
    ],
    "ISL": [
        { value: "ADM", text: "Admiralty" },
        { value: "CAB", text: "Causeway Bay" },
        { value: "CEN", text: "Central" },
        { value: "CHW", text: "Chai Wan" },
        { value: "FOH", text: "Fortress Hill" },
        { value: "HFC", text: "Heng Fa Chuen" },
        { value: "HKU", text: "HKU" },
        { value: "KET", text: "Kennedy Town" },
        { value: "NOP", text: "North Point" },
        { value: "QUB", text: "Quarry Bay" },
        { value: "SWH", text: "Sai Wan Ho" },
        { value: "SYP", text: "Sai Ying Pun" },
        { value: "SKW", text: "Shau Kei Wan" },
        { value: "SHW", text: "Sheung Wan" },
        { value: "TAK", text: "Tai Koo" },
        { value: "TIH", text: "Tin Hau" },
        { value: "WAC", text: "Wan Chai" }
    ],
    "KTL": [
        { value: "CHH", text: "Choi Hung" },
        { value: "DIH", text: "Diamond Hill" },
        { value: "HOM", text: "Ho Man Tin" },
        { value: "KOB", text: "Kowloon Bay" },
        { value: "KOT", text: "Kowloon Tong" },
        { value: "KWT", text: "Kwun Tong" },
        { value: "LAT", text: "Lam Tin" },
        { value: "LOF", text: "Lok Fu" },
        { value: "MOK", text: "Mong Kok" },
        { value: "NTK", text: "Ngau Tau Kok" },
        { value: "PRE", text: "Prince Edward" },
        { value: "SKM", text: "Shek Kip Mei" },
        { value: "TIK", text: "Tiu Keng Leng" },
        { value: "WHA", text: "Whampoa" },
        { value: "WTS", text: "Wong Tai Sin" },
        { value: "YMT", text: "Yau Ma Tei" },
        { value: "YAT", text: "Yau Tong" }
    ]
};